networks:
  hm-backend:
    driver: bridge
    attachable: true
  hm-frontend:
    driver: bridge
    attachable: true

services:
  redis:
    image: redis:latest
    container_name: redis-db
    networks:
      - hm-backend
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: var/storage/redis/
        target: /data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=2
    command: bash -c "redis-server --appendonly yes"
  webserver:
    image: jeebsm/house_metric_backend:latest
    container_name: webservice
    networks:
      - hm-backend
    environment:
      - DEPLOY_ENV=prod
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: /var/storage
        target: /house_backend/storage
    restart: always
    tty: true
  ui:
    image: jeebsm/house_metric_frontend:latest
    container_name: meter-ui
    networks:
      - hm-backend
      - hm-frontend
    environment:
      - DEPLOY_ENV=prod
    ports:
      - 443:3000
      - 80:3000
    restart: always
    tty: true