x-common:
    - &common
        networks:
          - hm-backend
    - &project_common
      env_file:
        - .env

networks:
    hm-backend:
      driver: bridge
      attachable: true

services:
  house-backend:
    <<: [*common, *project_common]
    build:
      context: /house_backend
      dockerfile: Dockerfile
    container_name: house-backend
    environment:
      - DEPLOY_ENV=development
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - type: bind
        source: house_backend/
        target: /house_backend
    restart: always
    tty: true
  meter-ui:
    <<: [*common, *project_common]
    build:
      context: /meter_ui
      dockerfile: Dockerfile
    container_name: meter-ui
    environment:
      - DEPLOY_ENV=development
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: meter_ui/
        target: /usr/app/src
        read_only: true
    restart: always
    tty: true