networks:
  hm-backend:
    driver: bridge
    attachable: true
  hm-frontend:
    driver: bridge
    attachable: true

services:
  redis:
    image: redis:latest
    container_name: redis-db
    networks:
      - hm-backend
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: house_backend/storage/redis/
        target: /data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=2
    command: bash -c "redis-server --appendonly yes"
  house-backend:
    build:
      context: /house_backend
      dockerfile: Dockerfile
    container_name: house-backend
    networks:
      - hm-backend
    environment:
      - DEPLOY_ENV=development
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - type: bind
        source: house_backend/
        target: /house_backend
    restart: always
    tty: true
  meter-ui:
    build:
      context: /meter_ui
      dockerfile: Dockerfile
    container_name: meter-ui
    environment:
      - DEPLOY_ENV=development
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: meter_ui/
        target: /usr/app/src
        read_only: true
    restart: always
    tty: true